
server:
  port: 8888 #服务端口
spring:
  application:
    name: api-gateway-zuul #指定服务名


eureka:
  client:
    registry-fetch-interval-seconds: 5 # 获取服务列表的周期：5s
    service-url:
      defaultZone: http://localhost:8800/eureka/,http://localhost:8801/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1



zuul:
  prefix: /api # 添加路由前缀
  routes:  # \可以不配置映射  默认  访问 服务名/**  及映射到对应服务的路径
    ribbon-provider:  /ribbon-provider/**

