server:
  port: 7777


# rabbitmq配置
spring:
    rabbitmq:
      addresses: 129.204.183.175:5672
      username: admin
      password: admin
      # 对 rabbitmqTemplate 进行监听,当消息由于server的原因无法到达queue时，就会被监听到，以便执行ReturnCallback方法
      publisher-confirms: true
      publisher-returns: true
      # mandatory：交换器无法根据自身类型和路由键找到一个符合条件的队列时的处理方式
        #true：RabbitMQ会调用Basic.Return命令将消息返回给生产者
        #false：RabbitMQ会把消息直接丢弃
      template:
            mandatory: true
      listener:
              simple:
                    # 消费端手动确认
                acknowledge-mode: manual
                    # 并发消费
                concurrency:  5
                max-concurrency: 10



