
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8800/eureka/,http://localhost:8801/eureka/
  instance:
      lease-expiration-duration-in-seconds: 90 #\u670D\u52A1\u5931\u6548\u65F6\u95F4\uFF0C\u9ED8\u8BA4\u503C90\u79D2
      lease-renewal-interval-in-seconds: 30 #\u670D\u52A1\u7EED\u7EA6(renew)\u7684\u95F4\u9694\uFF0C\u9ED8\u8BA4\u4E3A30\u79D2

server:
  port: 8803
spring:
  application:
    name: ribbon-provider